# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hrm_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1075, 871)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.u_code_droplist = CodeDropList(self.centralwidget)
        self.u_code_droplist.setGeometry(QtCore.QRect(890, 50, 140, 600))
        self.u_code_droplist.setObjectName("u_code_droplist")
        self.u_op_droplist = OperationDropList(self.centralwidget)
        self.u_op_droplist.setGeometry(QtCore.QRect(740, 50, 140, 730))
        self.u_op_droplist.setObjectName("u_op_droplist")
        self.u_input_list = InputListWidget(self.centralwidget)
        self.u_input_list.setGeometry(QtCore.QRect(75, 90, 50, 500))
        self.u_input_list.setObjectName("u_input_list")
        self.u_output_list = OutputListWidget(self.centralwidget)
        self.u_output_list.setGeometry(QtCore.QRect(625, 90, 50, 500))
        self.u_output_list.setObjectName("u_output_list")
        self.u_register_group = RegisterTableWidget(self.centralwidget)
        self.u_register_group.setGeometry(QtCore.QRect(220, 400, 302, 162))
        self.u_register_group.setObjectName("u_register_group")
        self.u_register_group.setColumnCount(0)
        self.u_register_group.setRowCount(0)
        self.u_desc = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.u_desc.setGeometry(QtCore.QRect(270, 50, 221, 81))
        self.u_desc.setObjectName("u_desc")
        self.u_input_label = QtWidgets.QLabel(self.centralwidget)
        self.u_input_label.setGeometry(QtCore.QRect(80, 60, 41, 16))
        self.u_input_label.setObjectName("u_input_label")
        self.u_output_label = QtWidgets.QLabel(self.centralwidget)
        self.u_output_label.setGeometry(QtCore.QRect(630, 60, 41, 16))
        self.u_output_label.setObjectName("u_output_label")
        self.u_operation_label = QtWidgets.QLabel(self.centralwidget)
        self.u_operation_label.setGeometry(QtCore.QRect(790, 20, 41, 16))
        self.u_operation_label.setObjectName("u_operation_label")
        self.u_code_label = QtWidgets.QLabel(self.centralwidget)
        self.u_code_label.setGeometry(QtCore.QRect(940, 20, 41, 16))
        self.u_code_label.setObjectName("u_code_label")
        self.u_register_group_label = QtWidgets.QLabel(self.centralwidget)
        self.u_register_group_label.setGeometry(QtCore.QRect(350, 370, 41, 16))
        self.u_register_group_label.setObjectName("u_register_group_label")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(250, 620, 239, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.u_next_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.u_next_btn.setObjectName("u_next_btn")
        self.horizontalLayout.addWidget(self.u_next_btn)
        self.u_pause_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.u_pause_btn.setObjectName("u_pause_btn")
        self.horizontalLayout.addWidget(self.u_pause_btn)
        self.u_state_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.u_state_btn.setObjectName("u_state_btn")
        self.horizontalLayout.addWidget(self.u_state_btn)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(350, 150, 44, 61))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.u_pointer_label = QtWidgets.QLabel(self.layoutWidget1)
        self.u_pointer_label.setObjectName("u_pointer_label")
        self.verticalLayout.addWidget(self.u_pointer_label)
        self.u_pointer = Pointer(self.layoutWidget1)
        self.u_pointer.setObjectName("u_pointer")
        self.verticalLayout.addWidget(self.u_pointer)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1075, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.u_desc.setPlainText(_translate("MainWindow", "关卡描述：\n"
"将输入框中的所有东西搬入输出框"))
        self.u_input_label.setText(_translate("MainWindow", "输入框"))
        self.u_output_label.setText(_translate("MainWindow", "输出框"))
        self.u_operation_label.setText(_translate("MainWindow", "操作框"))
        self.u_code_label.setText(_translate("MainWindow", "代码框"))
        self.u_register_group_label.setText(_translate("MainWindow", "地址"))
        self.u_next_btn.setText(_translate("MainWindow", "下一步"))
        self.u_pause_btn.setText(_translate("MainWindow", "暂停"))
        self.u_state_btn.setText(_translate("MainWindow", "开始"))
        self.u_pointer_label.setText(_translate("MainWindow", "pointer"))
        self.u_pointer.setText(_translate("MainWindow", "number"))
from InputListWidget import InputListWidget, OutputListWidget
from MyWidget import CodeDropList, OperationDropList
from Pointer import Pointer
from RegisterTableWidget import RegisterTableWidget
