# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hrm_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(250, 40, 311, 431))
        self.widget.setObjectName("widget")
        self.u_op_droplist = OperationDropList(self.widget)
        self.u_op_droplist.setGeometry(QtCore.QRect(170, 20, 141, 361))
        self.u_op_droplist.setObjectName("u_op_droplist")
        self.u_code_droplist = CodeDropList(self.centralwidget)
        self.u_code_droplist.setGeometry(QtCore.QRect(580, 40, 141, 411))
        self.u_code_droplist.setObjectName("u_code_droplist")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
from MyWidget import CodeDropList, OperationDropList
